// Generated by delombok at Sun Jun 19 15:25:27 EDT 2022
package com.vgrazi.example;

import java.util.Arrays;
import java.util.List;

public class User {
    private final int userID;
    private long birthday;
    private final String name;
    private final List<String> friends = List.of("William", "Alok", "Heather");
    private final String address;

    public static void main(String[] args) {
        User user = new User(123, "John Jones", "123 Main");
        user.someMethod();
        System.out.println(user);
    }

    public static void mainx(String[] args) {
        System.out.println("args = " + Arrays.deepToString(args));
        System.out.println();
    }

    /**
     * Some method
     */
    public void someMethod() {
        double val = Math.random();
    }

    @java.lang.SuppressWarnings("all")
    public User(final int userID, final String name, final String address) {
        this.userID = userID;
        this.name = name;
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    public int getUserID() {
        return this.userID;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getFriends() {
        return this.friends;
    }

    @java.lang.SuppressWarnings("all")
    public String getAddress() {
        return this.address;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof User)) return false;
        final User other = (User) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getUserID() != other.getUserID()) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$friends = this.getFriends();
        final java.lang.Object other$friends = other.getFriends();
        if (this$friends == null ? other$friends != null : !this$friends.equals(other$friends)) return false;
        final java.lang.Object this$address = this.getAddress();
        final java.lang.Object other$address = other.getAddress();
        if (this$address == null ? other$address != null : !this$address.equals(other$address)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof User;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getUserID();
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $friends = this.getFriends();
        result = result * PRIME + ($friends == null ? 43 : $friends.hashCode());
        final java.lang.Object $address = this.getAddress();
        result = result * PRIME + ($address == null ? 43 : $address.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "User(userID=" + this.getUserID() + ", name=" + this.getName() + ", friends=" + this.getFriends() + ")";
    }

    public long getAge() {
        return System.currentTimeMillis() - birthday;
    }
}
